language: go
go:
- 1.12.x
- master
os:
- osx
osx_image: xcode10.1
dist: trusty
env:
- GO111MODULE=on
before_install:
- go get github.com/mattn/goveralls
install: true
script:
- make test-cover
- goveralls -coverprofile=cover.out -service=travis-ci
- make build
